# Generated by Django 5.0.1 on 2026-01-29 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INTENT_RECEIVED', 'Intent Received'), ('AGENT_SELECTED', 'Agent Selected'), ('CONTEXT_FETCHED', 'Context Fetched'), ('AGENT_RESPONSE', 'Agent Response'), ('ACTIONS_APPLIED', 'Actions Applied'), ('AUDIT_LOGGED', 'Audit Logged'), ('ERROR_OCCURRED', 'Error Occurred')], max_length=50)),
                ('payload', models.JSONField(help_text='Event data and context')),
                ('metadata', models.JSONField(blank=True, help_text='Additional metadata', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('parent_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='agents.event')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='agents.agentsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('USER_ACTION', 'User Action'), ('AGENT_ACTION', 'Agent Action'), ('SYSTEM_ACTION', 'System Action'), ('DATA_MODIFICATION', 'Data Modification'), ('AUTHENTICATION', 'Authentication')], max_length=50)),
                ('action', models.CharField(help_text='Description of the action', max_length=200)),
                ('resource', models.CharField(blank=True, help_text='Resource affected (e.g., Task:123)', max_length=200, null=True)),
                ('details', models.JSONField(help_text='Detailed information about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.event')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('USER_PREFERENCES', 'User Preferences'), ('CONVERSATION_HISTORY', 'Conversation History'), ('TASK_CONTEXT', 'Task Context'), ('TEMPORAL_CONTEXT', 'Temporal Context'), ('CUSTOM', 'Custom')], max_length=50)),
                ('key', models.CharField(help_text='Context key identifier', max_length=100)),
                ('value', models.JSONField(help_text='Context data')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this context expires', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='agents.agentsession')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session', 'context_type'], name='agents_agen_session_efe27e_idx')],
                'unique_together': {('session', 'context_type', 'key')},
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'timestamp'], name='agents_even_event_t_9063d6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['session', 'timestamp'], name='agents_even_session_c02d11_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'timestamp'], name='agents_audi_action__e0913f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='agents_audi_user_id_7fadb0_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['session', 'timestamp'], name='agents_audi_session_34630b_idx'),
        ),
    ]
