# Generated by Django 5.0.1 on 2026-03-11 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_event_auditlog_agentcontext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', help_text="User's timezone for scheduling and reminders", max_length=50)),
                ('dietary_preferences', models.JSONField(blank=True, default=dict, help_text="e.g. {'type': 'vegetarian', 'allergies': ['nuts'], 'cuisine': ['Indian', 'Italian']}")),
                ('work_hours', models.JSONField(blank=True, default=dict, help_text="e.g. {'start': '09:00', 'end': '18:00', 'days': ['Mon','Tue','Wed','Thu','Fri']}")),
                ('fitness_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('health_conditions', models.JSONField(blank=True, default=list, help_text='List of conditions agents should be aware of')),
                ('learning_style', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('reading', 'Reading/Writing'), ('kinesthetic', 'Kinesthetic')], default='visual', max_length=20)),
                ('goals', models.JSONField(blank=True, default=list, help_text="e.g. [{'goal': 'Lose 5kg', 'deadline': '2026-06-01', 'category': 'wellness'}]")),
                ('about_me', models.TextField(blank=True, default='', help_text='Anything the user wants agents to always know about them')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
