# Generated by Django 5.0.1 on 2026-03-14 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='agent_type',
            field=models.CharField(choices=[('meal_planner', 'Meal Planner'), ('productivity', 'Productivity Agent'), ('study_buddy', 'Study Buddy'), ('wellness', 'Wellness Agent'), ('habit_coach', 'Habit Coach'), ('orchestrator', 'Orchestrator')], max_length=50),
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('health', 'Health & Fitness'), ('productivity', 'Productivity'), ('mindfulness', 'Mindfulness'), ('learning', 'Learning'), ('social', 'Social'), ('self_care', 'Self Care'), ('finance', 'Finance'), ('other', 'Other')], default='other', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text='e.g. [0,2,4] for Mon/Wed/Fri')),
                ('reminder_time', models.TimeField(blank=True, help_text='When to remind the user', null=True)),
                ('target_count', models.IntegerField(default=1, help_text='How many times per day (e.g., 8 glasses of water)')),
                ('current_streak', models.IntegerField(default=0)),
                ('best_streak', models.IntegerField(default=0)),
                ('total_completions', models.IntegerField(default=0)),
                ('color', models.CharField(default='#8B5CF6', help_text='Hex color for UI display', max_length=7)),
                ('icon', models.CharField(default='✅', help_text='Emoji icon', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_streak', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0, help_text='For countable habits (e.g., glasses of water)')),
                ('notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.habit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='agents_habi_user_id_5a73e3_idx'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['habit', 'date'], name='agents_habi_habit_i_6f7d03_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together={('habit', 'date')},
        ),
    ]
