# Generated by Django 5.0.1 on 2026-05-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agents", "0005_alter_userprofile_dietary_preferences"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique key for deduplication (UUID from caller)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["idempotency_key"], name="agents_even_idempot_2adcd8_idx"
            ),
        ),
    ]
