# Generated by Django 5.0.1 on 2026-05-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_calendarevent_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]