"""
Apply structured actions generated by agents.

Supported input format in agent responses:
```json
{
  "actions": [
    {"action": "create_task", "data": {"title": "..."}}
  ]
}
```
"""
from __future__ import annotations

import json
import logging
import re
from typing import Any, Dict, List, Optional

from asgiref.sync import sync_to_async

from agents.models import AgentSession, User, Habit
from .save_helper import (
    save_task,
    save_meal_plan,
    save_study_session,
    save_wellness_activity,
)

logger = logging.getLogger(__name__)


class ActionApplier:
    """Extract and apply structured actions from LLM responses."""

    ACTION_HANDLERS = {
        'create_task': 'task',
        'create_meal_plan': 'meal',
        'create_study_session': 'study',
        'create_wellness_activity': 'wellness',
        'create_habit': 'habit',
    }

    def extract_actions(self, response_text: str) -> List[Dict[str, Any]]:
        """
        Extract actions from fenced JSON blocks or full JSON responses.

        Returns a list of normalized actions:
        [{"action": "create_task", "data": {...}}]
        """
        if not response_text or not isinstance(response_text, str):
            return []

        payload_candidates: List[Any] = []

        fenced_blocks = re.findall(r"```json\s*(.*?)\s*```", response_text, flags=re.IGNORECASE | re.DOTALL)
        for block in fenced_blocks:
            parsed = self._safe_json_loads(block)
            if parsed is not None:
                payload_candidates.append(parsed)

        stripped = response_text.strip()
        if stripped.startswith('{') or stripped.startswith('['):
            parsed = self._safe_json_loads(stripped)
            if parsed is not None:
                payload_candidates.append(parsed)

        extracted: List[Dict[str, Any]] = []
        for payload in payload_candidates:
            actions = self._actions_from_payload(payload)
            extracted.extend(actions)

        normalized = []
        for item in extracted:
            action_name = item.get('action') or item.get('type')
            data = item.get('data') if isinstance(item.get('data'), dict) else {}
            if action_name in self.ACTION_HANDLERS:
                normalized.append({'action': action_name, 'data': data})

        return normalized

    def _safe_json_loads(self, text: str) -> Optional[Any]:
        try:
            return json.loads(text)
        except Exception:
            return None

    def _actions_from_payload(self, payload: Any) -> List[Dict[str, Any]]:
        if isinstance(payload, dict):
            if isinstance(payload.get('actions'), list):
                return [a for a in payload['actions'] if isinstance(a, dict)]
            if payload.get('action') or payload.get('type'):
                return [payload]
            return []

        if isinstance(payload, list):
            return [a for a in payload if isinstance(a, dict) and (a.get('action') or a.get('type'))]

        return []

    async def apply_actions(
        self,
        response_text: str,
        session: AgentSession,
        user: Optional[User],
    ) -> List[Dict[str, Any]]:
        """Apply extracted actions and return execution results."""
        actions = self.extract_actions(response_text)
        if not actions:
            return []

        applied: List[Dict[str, Any]] = []

        for item in actions:
            action_name = item['action']
            data = item.get('data', {})

            try:
                if action_name == 'create_task':
                    obj = await sync_to_async(save_task)(data=data, session=session, user=user)
                elif action_name == 'create_meal_plan':
                    obj = await sync_to_async(save_meal_plan)(data=data, session=session, user=user)
                elif action_name == 'create_study_session':
                    obj = await sync_to_async(save_study_session)(data=data, session=session, user=user)
                elif action_name == 'create_wellness_activity':
                    obj = await sync_to_async(save_wellness_activity)(data=data, session=session, user=user)
                elif action_name == 'create_habit':
                    obj = await self._create_habit(data, user)
                else:
                    obj = None

                applied.append({
                    'action': action_name,
                    'success': bool(obj),
                    'object_id': getattr(obj, 'id', None),
                })
            except Exception as exc:
                logger.warning("Failed applying action %s: %s", action_name, exc)
                applied.append({
                    'action': action_name,
                    'success': False,
                    'error': str(exc),
                })

        return applied

    async def _create_habit(self, data: Dict[str, Any], user: Optional[User]) -> Optional[Habit]:
        if not user or not user.is_authenticated:
            return None

        defaults = {
            'description': data.get('description', ''),
            'category': data.get('category', 'other'),
            'frequency': data.get('frequency', 'daily'),
            'target_count': data.get('target_count', 1),
            'icon': data.get('icon', '✅'),
            'color': data.get('color', '#8B5CF6'),
            'is_active': True,
        }

        name = data.get('name') or data.get('title')
        if not name:
            return None

        habit, _ = await sync_to_async(Habit.objects.update_or_create)(
            user=user,
            name=name,
            defaults=defaults,
        )
        return habit


action_applier = ActionApplier()
